version: "3.9"
services:
  web:
    build: .
    env_file: .env
    depends_on: [mongo]
    ports: ["8000:8000"]
    volumes:
      - app_data:/var/app/data
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports: ["27017:27017"]
  nginx:
    image: nginx:alpine
    depends_on: [web]
    ports: ["80:80"]
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  mongo_data:
  app_data:
